### ISSUE TITLE
Include `kytos/kytos_stats` on Test Analytics Dashboard

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/kytos_stats#2]
We'll also need to include `kytos/kytos_stats` on [Test Analytics Dashboard](https://kytos-tests.amlight.net/index.html), and also create internal GitLab projects to run its unit tests on a nightly basis. Our team uses this dashboard to have an overview of the current tests status, and also we link it on the release notes, so having `kytos/kytos_stats` there it'd be great before we consolidate the upcoming release notes for `2023.1`.

@gretelliz, can you help out with this one?

**Comment by gretelliz** [comment]
Sure

**Comment by gretelliz** [comment]
This issue has been solved by following the steps:

### Adding a Napp to the AmLight Kytos-ng Test Analytics Dashboard and also to daily e-mail report 

0. Make sure the Napp is included in Scrutinizer execution:

```
case: kytos_stats
Yes, it is https://scrutinizer-ci.com/g/kytos-ng/kytos_stats/
```

1. Add the unit tests to AmLight gitlab-ci daily execution

    1.1) create a gitlab-ci execution: 
    - Create a new project in https://gitlab.ampath.net/kytos and configure a new file (.gitlab-ci.yml)
    - Create a new schedule within the new project with the option CI/CD/Schedules.

    1.2) add the new test to amlight daily report (crontab script)

2. Add the new Napp to the Test Analytics dashboard app:
   - Include the repo on app.py

4. Deploy a new version of the Test Analytics dashboard

5. Validate if the Test Analytics dashboard is working as expetectd
