### ISSUE TITLE
Add a start time counter for helping monitoring

### ISSUE THREAD

**Issue by italovalcy** [kytos-ng/kytos_stats#7]
As descrived in [mef_eline#341](https://github.com/kytos-ng/mef_eline/issues/341), we lack a mechanism to identify when some services are actually down or they are just booting up. My suggestion is, as a workaround, we add the start time counter to kytos_stats, and then we can leverage this counter on zabbix_wrapper (or any other monitoring tool) to identity those booting moments.

**Comment by viniarck** [comment]
@italovalcy @gretelliz 

I'll add some comments to mef_eline#341 shortly. 

Regarding the workaround, maybe we could instead augment this core endpoint `GET localhost:8181/api/kytos/core/status` to include when the `APIServer` started? In fact, we already have a [`self.started_at`](https://github.com/kytos-ng/kytos/blob/master/kytos/core/controller.py#L366) keeping track right after the `Controller` instance is started and dispatched the tasks:

```
diff --git a/kytos/core/api_server.py b/kytos/core/api_server.py
index 8d9d788..8cc7819 100644
--- a/kytos/core/api_server.py
+++ b/kytos/core/api_server.py
@@ -146,7 +146,14 @@ class APIServer:
 
 
     def status_api(self, _request: Request):
         """Display kytos status using the route ``/kytos/status/``."""
-        return JSONResponse({"response": "running"})
+        uptime = self.napps_manager._controller.uptime()
+        return JSONResponse(
+            {
+                "response": "running",
+                "uptime_seconds": uptime.seconds if uptime else 0,
+                "started_at": self.napps_manager._controller.started_at,
+            }
+        )
```

```
❯ http localhost:8181/api/kytos/core/status
HTTP/1.1 200 OK
content-length: 90
content-type: application/json
date: Mon, 26 Jun 2023 19:33:30 GMT
server: uvicorn

{
    "response": "running",
    "started_at": "2023-06-26T19:31:53.776338+00:00",
    "uptime_seconds": 97
}

```

and then on zabbix_wrapper, depending on the endpoint, it could send a pre-request and check either `uptime_seconds or `started_at` and depending on the value returning a value that's considered unknown until we augment mef_eline? wdyt?
